name: rdf
channels:
  - conda-forge
dependencies:
  - python >3.8
  - pyscal3 >=3.1.5
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - pyyaml
  - ase 
  - networkx
  - pandas
  - owlready2
  - jupyter-book
  - plotly
  - ipywidgets
  - sphinx

