name: rdf
channels:
  - conda-forge
dependencies:
  - python >3.8
  - pyscal3 >=3.1.1
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - pyyaml
  - ase 
  - ipycytoscape
  - networkx
  - pandas
  - owlready2
  - sqlalchemy <2.0.0
  - rdflib-sqlalchemy
  - jupyter-book
  - plotly
  - ipywidgets
  - pip:
    - sphinx==5.3.0
    - sphinx_rtd_theme
    - myst_parser
    - furo
    - nbsphinx
    - sphinx_inline_tabs
    - sphinx_copybutton
    - sphinx_design
    - docutils==0.19

