name: rdf
channels:
  - conda-forge
dependencies:
  - python >3.8
  - pyscal3
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - pyyaml
  - ase 
  - ipycytoscape
  - networkx
  - sqlalchemy <2.0.0
  - rdflib-sqlalchemy
