name: rdf
channels:
  - conda-forge
dependencies:
  - python >3.8
  - conda-forge/label/pyscal_dev::pyscal
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - pyyaml
  - ase 
  - ipycytoscape
  - voila
  - plotly
  - jupyterlab-dash
